# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40a7f22d8d9fdb1118dcdd1c03d8a47701b9eef987584719ba790a6481b9cd7782698446ae357b265250ea089c671b078ddf5a823aeae381136b47bbbb6cac4

test:
  secret_key_base: 662edfb094eb3fd2b27f9bfc82c92b1a59f8283508e5b6d703e97e5a3b4dbcb61e0bff37cf755943d1b0efae36fba1812fb097fd6a50180c13c3151d7610685d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
